{
  "action": {
    "error": {
      "variety": [
        "Misdelivery"
      ],
      "vector": [
        "Unknown"
      ]
    }
  },
  "actor": {
    "internal": {
      "motive": [
        "NA"
      ],
      "variety": [
        "Unknown"
      ]
    }
  },
  "asset": {
    "assets": [
      {
        "variety": "U - Desktop"
      }
    ]
  },
  "attribute": {
    "confidentiality": {
      "data": [
        {
          "amount": 722,
          "variety": "Personal"
        }
      ],
      "data_disclosure": "Yes",
      "data_total": 722,
      "data_victim": [
        "Patient"
      ],
      "state": [
        "Unknown"
      ]
    }
  },
  "discovery_method": "Ext - customer",
  "impact": {
    "overall_rating": "Unknown"
  },
  "incident_id": "9D687722-21C5-4A7B-9E69-D5DA62423BFF",
  "plus": {
  "IOI_Impact_Score": 2,
  "IOI_media_coverage": "Yes",
  "IOI_under_1k_records": "Yes",
    "analysis_status": "Finalized",
    "analyst": "Spitler",
    "attribute": {
      "confidentiality": {
        "credit_monitoring": "U"
      }
    },
    "created": "2016-09-16T15:53:00Z",
    "dbir_year": 2016,
    "github": "6149",
    "master_id": "A12D5822-0F2F-4CC7-B18B-4E37694BBD63",
    "modified": "2016-09-16T15:56:00Z",
    "sub_source": "phidbr",
    "timeline": {
      "notification": {
        "day": 15,
        "month": 7,
        "year": 2015
      }
    }
  },
  "reference": "http://www.wtae.com/news/upmc-health-plan-reports-data-breach/34176994",
  "schema_version": "1.3.2",
  "security_incident": "Confirmed",
  "source_id": "vcdb",
  "summary": "Email misdelivery",
  "timeline": {
    "compromise": {
      "unit": "NA"
    },
    "discovery": {
      "unit": "Minutes"
    },
    "incident": {
      "day": 5,
      "month": 6,
      "year": 2015
    }
  },
  "victim": {
    "country": [
      "US"
    ],
    "employee_count": "Large",
    "industry": "524114",
    "region": [
      "019021"
    ],
    "state": "PA",
    "victim_id": "UPMC Health Plan"
  }
}
